language: groovy

jdk:
  - oraclejdk7

install: true

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui

env:
  - TERM=dumb

script:
  - gradle getGit -Pcomponent=HiveMind
  - gradle load
  - gradle runtime/component/HiveMind:test
